### PR TITLE
Dynamic non empty metrics

### PR DESCRIPTION
**Pull request by obourdon**
Subject says it all: fix for issue #20 (including also fix for issue #23 previously submitted as a separate pull request)

### CODE REVIEW

**Comment by obourdon** [comment]
cc: [@intelsdi-x/plugin-maintainers](https://github.com/orgs/intelsdi-x/teams/plugin-maintainers)

I really do not understand why this fails in Travis as the tests run ok on my system (tried both go 1.6.3 and 1.5.4, using 'TEST_SUITE=unit make check' command)

**Comment by IzabellaRaulin** [comment]
Hello @obourdon, it seems that _sc.CollectMetrics_ returns error: `sda is not valid disk` in this test which fails (see https://travis-ci.org/IzabellaRaulin/snap-plugin-collector-smart/jobs/155970289#L220)

So, it's related with [plugin.go#L224](https://github.com/obourdon/snap-plugin-collector-smart/blob/dynamic_non_empty_metrics/smart/plugin.go#L224) and iteration over devices in [L216](https://github.com/obourdon/snap-plugin-collector-smart/blob/dynamic_non_empty_metrics/smart/plugin.go#L216) which can not be found because `ListDevices()`  does not return "sda" (see [plugin_test.go#L43](https://github.com/obourdon/snap-plugin-collector-smart/blob/dynamic_non_empty_metrics/smart/plugin_test.go#L43)).


What do You think about:
- executing [listing available devices](https://github.com/obourdon/snap-plugin-collector-smart/blob/dynamic_non_empty_metrics/smart/plugin.go#L184) only when the incoming metric is requested for all system disks (so just move it under `if` statement in [plugin.go#L200](https://github.com/obourdon/snap-plugin-collector-smart/blob/dynamic_non_empty_metrics/smart/plugin.go#L200)
- and resigning from [range over devices if disk is specified and its validation](https://github.com/obourdon/snap-plugin-collector-smart/blob/dynamic_non_empty_metrics/smart/plugin.go#L215)-> because even such device does not exist `sc.DiskMetrics()` will return an appropriate error (see [plugin.go#L227](https://github.com/obourdon/snap-plugin-collector-smart/blob/dynamic_non_empty_metrics/smart/plugin.go#L227))

**Comment by obourdon** [comment]
Many thanks for this investigation @IzabellaRaulin, I will have a deeper look in this direction

However your error seems different than the one I am having on my side (expected 'sda' got '') and furthermore I still do not understand why running this by hand on my system just works perfectly well. The only reason I can think of is because I have 2 disks on my system and therefore sda and sdb are really available which should not be the case on your Travis CI machine

**Comment by IzabellaRaulin** [comment]
@obourdon, I added one check to get know why tests failed - without that I got exactly the same error as you. 

```
metrics, err := sc.CollectMetrics([]plugin.MetricType{
	{
		Namespace_: core.NewNamespace("intel", "disk", "smart", "sda").AddStaticElements(metric_ns...),
		Config_:    cfg,
	},
})

Convey("Asks reader to read metric from correct drive", func() {
	So(err, ShouldBeNil) // added during investigation; this returned `sda is not valid disk` what gave more information what had happened				
	So(drive_asked, ShouldEqual, "sda") // this returned "expected 'sda' got ''"
```

As you mentioned, the reason why tests passed on your machine is that you have 'sda' on your system. 

Renaming "sda" used in tests to another name (e.g. "my_disk" or "dut") might be a good point - I will open an issue about that.

**Comment by obourdon** [comment]
@IzabellaRaulin sorry to be "pushy" but is it possible to get this reviewed and potentially merged ASAP, we need to close our iteration gate today and would like to have this integrated in the official branch. 

Thanks for your understanding and help

cc: [@intelsdi-x/plugin-maintainers](https://github.com/orgs/intelsdi-x/teams/plugin-maintainers)

**Comment by IzabellaRaulin** [comment]
@obourdon, that's ok. The code looks good to me and also the plugin works properly, so it's ready to be merged. Thank You for your contribution.

**Comment by obourdon** [comment]
@IzabellaRaulin thanks a lot for integrating this today

**Pull request merged**
