### PR TITLE
Updated Godeps + Code refactoring

### PR DESCRIPTION
**Pull request by mkuculyma**
1. Updated Godeps
2. Code Refactoring:
	- simplified CollectMetics and DiskMetrics functions

### CODE REVIEW

**Comment by IzabellaRaulin** [comment]
Could you update collected metrics in README.md (prefix of namespace changed)- I'll really appreciate that.

**Comment by obourdon** [comment]
@IzabellaRaulin @mkuculyma : oops sorry about missing this part in my previous PR, keep forgetting about updating the docs :-(

**Comment by IzabellaRaulin** [comment]
@obourdon, no problem - we will cover that in this PR

**Comment by IRCody** [comment]
@mkuculyma, @IzabellaRaulin: Can we update the status of this PR?

**Comment by IzabellaRaulin** [comment]
I prepared two pull requests which cover this one. I split it into:
- Updated README and Godeps (see PR#32) - **important updates in README**
- Code refactoring: simplified CollectMetics and DiskMetrics function (see PR#33)

According to that, this pull request can be closed.

**Pull request closed without merging**
